'''
Reads a file generated by cProfile and prints the profiled stats.
'''
import argparse
import pstats

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('profile', help='path to profile file')
args = parser.parse_args()
p = pstats.Stats(args.profile)

p.strip_dirs()

# Sort configuration
# p.sort_stats('cumulative')
p.sort_stats('ncalls')
# p.sort_stats('pcalls')
# p.sort_stats('tottime')


# Print configuration
# p.print_callers(.5, 'init')
# p.print_callees()
p.print_stats(10)
